### ISSUE TITLE
Some recipes don't use ore:machineBlock* when they should

### ISSUE THREAD

**Issue by meerple** [TechReborn/TechReborn#1233]
Hi. I am playing with IC2 on ATM 3 v2.8. The pack removes the recipe for the TR machine block, because it was preventing IC2 machine blocks from being crafted and IC2 machine blocks can be used for TR recipes. But, the Alloy Smelter, Industrial Blast Furnace, Implosion Compressor, Matter Fabricator and Advanced Machine Casing recipes don't use ore dictionary machine blocks, so they aren't craftable. I used a CraftTweaker script to remove the recipes and add them back in with ore dic machine blocks. Thanks

[This is the script](https://pastebin.com/wqswx89T)

**Comment by drcrazy** [comment]
There is no Highly Advanced Machine block in IC2. This frame used for Matter Fabricator and Advanced Machine Casing.  Other recipes are fixed in MC 1.12.1

**Comment by meerple** [comment]
I am using Tech Reborn 2.6.11.177 on MC 1.12.1. Is there a newer version? Because these issues are still happening. The Highly Advanced Machine Frame has no recipe. The Matter Fabricator recipe uses Advanced Machine Frames, whose recipe is messed up. The Advanced Machine Casing uses Advanced Machine Frames. And I had to put my script back in to craft an Industrial Blast Furnace yesterday.

![1](https://user-images.githubusercontent.com/24219145/29674845-97e36278-88b0-11e7-87d9-1a8ee17de4b5.jpg)
![2](https://user-images.githubusercontent.com/24219145/29674846-97ea9cfa-88b0-11e7-8aeb-f04794f68a66.jpg)
![3](https://user-images.githubusercontent.com/24219145/29674848-97ee39be-88b0-11e7-967a-9b97a3b32a4b.jpg)
![4](https://user-images.githubusercontent.com/24219145/29674847-97ec0cca-88b0-11e7-91ef-a737d43e50d3.jpg)

**Comment by drcrazy** [comment]
TechReborn-1.12.1-2.6.12.181 should be available on curse soon. Issue fixed in builds >180 )
