### ISSUE TITLE
[1.12.2] (Forge version 14.23.0.2532 and higher) + (tech reborn) + latest IC2 = ShapelessRecipes = basic machine casing

### ISSUE THREAD

**Issue by Staegrin** [TechReborn/TechReborn#1340]
So I noticed this problem 8/11/2017 and at first I blamed the mod uppers. You could place any item into the crafting grid that didn't normally have a result when placed there and it would result in a hopper from uppers.

When Removing the mod the result from any such item in the crafting grid became a basic machine casing from IC2.
![2017-11-12_17 03 35](https://user-images.githubusercontent.com/8494635/32701371-1fec63ce-c7d4-11e7-90ed-84c7f8e94ef9.png)

After deactivating all the mods, I turned them back on one by one. I narrowed the source of it down to 
Techreborn 1.12.2-2.8.1.342
Reborncore 3.4.11.153
IC2 2.8.16-ex112
+Forge version equal or higher than 14.23.0.2532
The changelog for that version mentioned 
"Build 1.12.2-14.23.0.2532:
	zzzz:
		Fix the incorrect matching algorithm in ShapelessRecipes and
		ShapelessOreRecipe (#4472)"

Downgrading the forge version below 14.23.0.2532
![2017-11-12_17 09 59](https://user-images.githubusercontent.com/8494635/32701446-ece0796e-c7d5-11e7-8986-c9eeb22fe528.png)

Fixes the bug. Though there is still visible in JEI
![2017-11-12_17 57 19](https://user-images.githubusercontent.com/8494635/32701416-23d0376c-c7d5-11e7-8410-6829a033ee09.png)

That nothing in the grid = a basic machine casing (when hovering over it with the mouse it says recipe by tech reborn)

**Comment by modmuss50** [comment]
humm, strange. Ill have to take a look at this.

**Comment by Staegrin** [comment]
I think the team from applied energistics might know something about it because their latest version has 

"Fixes #3200: Cleanup recipe factories to prevent recipes from not working on servers with forge version 2532 or later. - fscan"

In the changelog pertaining to the change in forge.

**Comment by drcrazy** [comment]
Maybe forge will fix this.

https://github.com/MinecraftForge/MinecraftForge/pull/4472/files#r146108157

**Comment by drcrazy** [comment]
I hope this one is fixed. ) 
Feel free to reopen if not

**Comment by Staegrin** [comment]
Latest forge 2542 does not fix this.

I can still turn a block who has no 1x1 recipe normally into basic a machine casing.
![2017-11-14_10 52 10](https://user-images.githubusercontent.com/8494635/32773892-eed2ca28-c92a-11e7-8c5b-d8409f3893fa.png)

The recipe to turn a tech reborn basic machine frame into an IC2 basic machine casing also doesn't shown up in JEI. Only a blank crafting grid = IC2 basic machine casing
![2017-11-14_11 03 38](https://user-images.githubusercontent.com/8494635/32774112-914c5aee-c92b-11e7-9e58-5dea391cc328.png)

Might I suggest checking the code for the recipe in your mod. Just in case something went wrong?

**Comment by drcrazy** [comment]
I hope issue fixed in TR in this commit: https://github.com/TechReborn/TechReborn/commit/53c8033a9927d5a7bf1087f9197cbc34731487ee

Updated version of TR is not released to curse yet.

**Comment by Staegrin** [comment]
Latest forge 2542 does not fix this.

I can still turn a block who has no 1x1 recipe normally into basic a machine casing.
![2017-11-14_10 52 10](https://user-images.githubusercontent.com/8494635/32773892-eed2ca28-c92a-11e7-8c5b-d8409f3893fa.png)

The recipe to turn a tech reborn basic machine frame into an IC2 basic machine casing also doesn't shown up in JEI. Only a blank crafting grid = IC2 basic machine casing
![2017-11-14_11 03 38](https://user-images.githubusercontent.com/8494635/32774112-914c5aee-c92b-11e7-9e58-5dea391cc328.png)

Might I suggest checking the code for the recipe in your mod. Just in case something went wrong?

**Comment by Staegrin** [comment]
Is indeed fixed. Thanks for all the help.
