### ISSUE TITLE
Prevent the registration of an Item and its recipes if the ore doesn't exist

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#211]
To prevent this:
![2015-11-01_12 22 59](https://cloud.githubusercontent.com/assets/8685029/10868786/8636ef16-8099-11e5-91b5-3b05138acadf.png)

For example, I haven't Factorization that add DarkIron Ore, but techreborn register the items releated to this and the releated recipes.

**Comment by gigabit101** [comment]
this is already fixed

**Comment by Xen1290** [comment]
Thanks!

**Comment by Xen1290** [comment]
@gigabit101 @modmuss50 this isn't fixed, tested with latest version on jenkins, same result.

**Comment by Xen1290** [comment]
Also this on logs
[12:51:05] [Client thread/INFO] [TechReborn]: TechReborns Blocks Loaded
[12:51:05] [Client thread/INFO] [TechReborn]: TechReborns Items Loaded
[12:51:06] [Client thread/INFO] [TechReborn]: Started to load all parts
[12:51:06] [Client thread/INFO] [TechReborn]: Shapless Recipes Added
[12:51:06] [Client thread/INFO] [TechReborn]: Shapped Recipes Added
[12:51:06] [Client thread/INFO] [TechReborn]: Smelting Recipes Added
[12:51:06] [Client thread/INFO] [TechReborn]: Failed to Load Grinder Recipe for Charged Certus Quartz Ore
[12:51:06] [Client thread/INFO] [TechReborn]: IC2 Recipes Removed
[12:51:06] [Client thread/INFO] [TechReborn]: Added Expensive IC2 Recipes
[12:51:06] [Client thread/INFO] [TechReborn]: Failed to Load Grinder Recipe for Ardite Ore
[12:51:06] [Client thread/INFO] [TechReborn]: Failed to Load Grinder Recipe for Cobalt Ore
[12:51:06] [Client thread/INFO] [TechReborn]: Failed to Load Grinder Recipe for Dark Iron Ore
[12:51:06] [Client thread/INFO] [TechReborn]: Failed to Load Grinder Recipe for Charged Certus Quartz Ore
[12:51:06] [Client thread/INFO] [TechReborn]: WorldGen Loaded
[12:51:07] [Client thread/INFO] [TechReborn]: Initialization Complete

**Comment by modmuss50** [comment]
Mind resetting your config? Eu power could be disabled in there?

**Comment by Xen1290** [comment]
EU power? For #229 I think you mean, I've resetted the configs, same thing. In #229 I've posted my config file.
