### ISSUE TITLE
Near-zero energy amounts are displayed with far too much precision

### ISSUE THREAD

**Issue by The-Fireplace** [TechReborn/TechReborn#2399]
**Describe the bug**
When energy stored is near-zero, it gets displayed with way too much precision considering that it's an unusably tiny fraction of a unit of energy.

**Steps to Reproduce**
- Have machines that are using energy with a setup like the following, then run out of power
- Open the middle batbox and see that energy amounts are rapidly growing smaller but never quite hitting zero.

**Screenshots**
![image](https://user-images.githubusercontent.com/5914284/119244180-85f3b680-bb33-11eb-8023-8609058008d3.png)
![image](https://user-images.githubusercontent.com/5914284/119244186-8b510100-bb33-11eb-9109-eb441935f127.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric
 - Tech Reborn: v3.8.3+build.231

**Additional Context**
I'm guessing it's the residual power in cables transferring smaller and smaller amounts out. If that's the case, might I suggest just transferring all of it once it hits a certain fraction of a unit?

**Comment by drcrazy** [comment]
Should be fixed by f75447f605527dfcc885ba35d0b37166f08174aa

**Comment by Ayutac** [comment]
@drcrazy Apparently still persists in energy transfer rates, shown here in 5.0.6 TR

![2021-09-01_17 42 04](https://user-images.githubusercontent.com/7873396/131702595-feb2fcbd-c7d5-41ba-b92c-cfef1e6b2de8.png)
