### ISSUE TITLE
Hoppers don't work with the Iron Furnace

### ISSUE THREAD

**Issue by Hobby-boy** [TechReborn/TechReborn#700]
The iron furnace doesn't accept items from hoppers. When putting a hopper on top of the furnace, and putting a smeltable item like ore or stone into the hopper, the item doesn't pass into the furnace at all. 

Using 1.3.4.11 for 1.10.2 with Forge 12.18.1.2011

**Comment by PrincessOfEvil** [comment]
Fixed in dev.

**Comment by Flow86** [comment]
still a problem here I think, a side attached hopper puts items in output slot, not in "fuel" slot with 1.11.2-2.0.9.25

or is the hopper layout changed here intentionally? 
Standard furnace has top -> top, side -> "fuel", bottom -> output

**Comment by ghost** [comment]
This has not been fixed yet.
