### ISSUE TITLE
bug with ore config file

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#794]
It seems that ores config file (ores.hjson) regenerates at each time Minecraft is loaded. In fact it overwrite at the end of the current config and add again the same config. The file become quickly fucking big with a config that repeat it without end. It seems too that now the TechReborn don't generate more at all in the world.

**Comment by modmuss50** [comment]
What version are you using? Please check with the beta on curse as I think I fixed it

**Comment by modmuss50** [comment]
No its still an issue, I will look into it

**Comment by 0Navis0** [comment]
It still doesn't work, all the ore config other than end other regenerate them in the end ores category at each launching. There are still no ores that spawn in the world. I use the last TechReborn version.

**Comment by modmuss50** [comment]
Fixed: https://github.com/TechReborn/TechReborn/commit/9ffdc3e36e543e5be191eb1b4aec5250102b5fb2

**Comment by 0Navis0** [comment]
Now the config is fine, but the ores still don't spawn. :(

**Comment by modmuss50** [comment]
fucking hell, try deleting the ores.hjson? I might just get rid of that file, and have a basic config to enable/disable them.

**Comment by 0Navis0** [comment]
It still doesn't work :(

**Comment by modmuss50** [comment]
Uhh

**Comment by modmuss50** [comment]
Thanks for trying

**Comment by 0Navis0** [comment]
You're welcome ;)

**Comment by modmuss50** [comment]
I think I tracked the issue down, going to test, then push to curse

**Comment by modmuss50** [comment]
Ok, I hope this fixes it: https://github.com/TechReborn/TechReborn/commit/59bd497893da0f043d090c195fcd9dcd878aa3c9

**Comment by Ananka59** [comment]
ok, waiting the update in curse =)

**Comment by modmuss50** [comment]
https://minecraft.curseforge.com/projects/techreborn/files/2342766

**Comment by Ananka59** [comment]
nice, i try it now

**Comment by Ananka59** [comment]
WORKING!  Thanks for reactivity !
