### ISSUE TITLE
Some machines not syncing GUI state correctly

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#88]
Some machines either don't give info or give it at odd times.

Eg, 

Industrial Electrolyzer won't say if it has power or progress, but will make progress.
![electrdoesnt 1](https://cloud.githubusercontent.com/assets/7843312/8890091/24ab43fa-3337-11e5-90e3-9862eea27db0.png)

Centrifuge won't show if its accepted power until its been giving both components to a recipe, but then won't show progress bar
![centri not update 2](https://cloud.githubusercontent.com/assets/7843312/8890094/383049a2-3337-11e5-9717-de8917ef2f94.png)
![centri not update 1](https://cloud.githubusercontent.com/assets/7843312/8890093/382fae02-3337-11e5-829a-ef8a6a19a613.png)

Example of one working fine is the Assembling machine, showing progress and power in realtime. 
![assembldoes 1](https://cloud.githubusercontent.com/assets/7843312/8890096/62c52340-3337-11e5-9821-f8e99b9ce6a9.png)
![assembldoes 2](https://cloud.githubusercontent.com/assets/7843312/8890097/62c636a4-3337-11e5-9e81-a194c0607df7.png)

**Comment by modmuss50** [comment]
Industrial Electrolyzer - looks fine to me. What version are you running?

**Comment by modmuss50** [comment]
All of this was fixed in newer versions, works fine on our end

**Comment by TheQuantumGeneral** [comment]
Apologies, that's what reporting bugs at 2am gets me.

Still have a few issues with it in 0.1.715 with Rolling Machine and Centrifuge not updating Power bar till I relog with singleplayer

**Comment by TheQuantumGeneral** [comment]
Also, all the WAILA tooltips seem to be showing power higher than the max value, and in the Rolling Machine this has caused the power bar to fill incorrectly. Every machine is showing a fill value higher than its max in WAILA, but only the rolling machine could I notice it affecting the bar. 

![2015-07-26_02 00 35](https://cloud.githubusercontent.com/assets/7843312/8890208/e7da4f6c-333a-11e5-9898-3ae3edc5b145.png)
![2015-07-26_02 04 36](https://cloud.githubusercontent.com/assets/7843312/8890209/e7db5650-333a-11e5-8ede-112013f8a955.png)

**Comment by TheQuantumGeneral** [comment]
Still no progress bar on centrifuge on my end either
![2015-07-26_02 10 02](https://cloud.githubusercontent.com/assets/7843312/8890232/9a547c44-333b-11e5-9562-f8e48165e3c6.png)

**Comment by modmuss50** [comment]
We think that the over power issue is an issue with ic2, because when we tried to add it for eu, it showed the same thing.

**Comment by Carbon-Ghost** [comment]
Small question, can we change the GUI of the centrifuge to be more user friendly ? One may think that the output slots are assigned to a side of the machine, I can do the GUI if you want ^^

**Comment by modmuss50** [comment]
@Carbon-Ghost that could be a good idea :)

**Comment by modmuss50** [comment]
Only issue here is the centrifuge, but im going to wait for @Carbon-Ghost s gui texture before I fix this.

**Comment by TheQuantumGeneral** [comment]
A thought to consider if you're redesigning the GUI. The centrifuge could do with a fluid tank. One of the main appeals of it in the old days was the ability to pump lava into it to make various resources.

**Comment by Carbon-Ghost** [comment]
Yeah I remember that, so GUI will be same size as old centrifuge GUI, except things will be more linear, I am thinking doing similar to the electrolyser GUI, we're input is in the top, output at bottom, and 1 inpu fluid tank at the top and cell slot at the top ^^ Is that ok ?

**Comment by modmuss50** [comment]
That should be ok.

**Comment by Carbon-Ghost** [comment]
I finished the GUI, the only thing you will need to add is the battery slot + lightning bolt + upgrade slots, I am not sure where to put them, as there is many possible ways to do it, so I let you guys be the judge ;)

**Comment by Carbon-Ghost** [comment]
http://imgur.com/P89KYTE

**Comment by TheQuantumGeneral** [comment]
Might be nostalgia but I kind of prefer the old one, sort of made sense from a centrifuge point of view. I'm not the judge though.

**Comment by modmuss50** [comment]
config?

**Comment by TheQuantumGeneral** [comment]
Its just a GUI, people will adapt, I already have, I like the new one. It's functional and non confusing.

**Comment by Carbon-Ghost** [comment]
Yeah, same for me, although I also love the old GUI, I do that for new players sake, as even me had some trouble understanding how the GUI worked... Our goal is to make new people and old people who began hating GT because of the old flamewar rediscover the mod after all ;) Also, I can change the fluid tank but I changed it and removed the lava text so you guys can use the tank for other fluids, plus it looks more appealing that it's a tank ^^

Also, I'm also going to change some tank icon in GUIs, so no worries it will all be the same style :) Unless you don't like it :c 

Also, I forgot to say it here but I said it in my texture todo list "issue" thread that I leave you guys to add the upgrade and battery slot + lightning bolt because I just can't decide where should I put it, it should be on the right, but I can't center it without wanting to move it again, if you guys are also stuck, I will add it later ^^ But basically wanted you opinion ^^''

**Comment by Carbon-Ghost** [comment]
Also because of the text ^^''

**Comment by modmuss50** [comment]
I will get it in game then we can see where to put the slots and look into the tank abut more

**Comment by Carbon-Ghost** [comment]
Kk ^^

**Comment by modmuss50** [comment]
Are there still issues here?

**Comment by TheQuantumGeneral** [comment]
Ill check the latest build later tonight but 755 still has issues with the centrifuge.

**Comment by modmuss50** [comment]
Ok thanks, it would be easier if you make new issues so I can track what needs to be done

**Comment by TheQuantumGeneral** [comment]
Will do

**Comment by modmuss50** [comment]
Im closing, if I didnt fix anything make a new issue for it
